import React, { useEffect, useMemo, useState } from 'react';
import { BookOpen, Landmark, Plus, ReceiptText } from 'lucide-react';
import { dataService } from '../services/dataService';
import Papa from 'papaparse';

export default function AccountingModule({ isMobile }) {
  const [data,setData]=useState({accounts:[],entries:[],items:[],bank:[]});
  const [tab,setTab]=useState('receivables');
  const [form,setForm]=useState({kind:'receivable',counterparty:'',description:'',amount:'',due_date:''});
  const [journal,setJournal]=useState({description:'',debit_account:'',credit_account:'',amount:''});
  const load=()=>dataService.getAccountingOverview().then(setData);
  useEffect(()=>{load().catch(console.error)},[]);
  const pending=useMemo(()=>data.items.filter(x=>x.status!=='paid'),[data.items]);
  const save=async()=>{if(!form.counterparty||!form.description||Number(form.amount)<=0)return;await dataService.addPayableReceivable({...form,amount:Number(form.amount),paid_amount:0,status:'pending',due_date:form.due_date||null});setForm({kind:'receivable',counterparty:'',description:'',amount:'',due_date:''});await load();};
  const postJournal=async()=>{if(!journal.description||!journal.debit_account||!journal.credit_account||Number(journal.amount)<=0)return;await dataService.postJournalEntry({entry_date:new Date().toISOString().slice(0,10),description:journal.description},[{account_id:journal.debit_account,debit:Number(journal.amount),credit:0},{account_id:journal.credit_account,debit:0,credit:Number(journal.amount)}]);setJournal({description:'',debit_account:'',credit_account:'',amount:''});await load();};
  const importBank=event=>{const file=event.target.files?.[0];if(!file)return;Papa.parse(file,{header:true,skipEmptyLines:true,complete:async result=>{const rows=result.data.map(r=>({transaction_date:r.fecha||r.date||r.Fecha,description:r.descripcion||r.description||r.Descripcion||'Movimiento bancario',amount:Number(String(r.monto||r.amount||r.Monto||0).replace(',','.')),reference:r.referencia||r.reference||null})).filter(r=>r.transaction_date&&Number.isFinite(r.amount));if(rows.length)await dataService.addBankStatementLines(rows);await load();}})};
  const field={height:42,border:'1px solid var(--border-color)',borderRadius:12,padding:'0 12px',background:'#fff'};
  return <div className="animate-fade-in" style={{paddingBottom:60}}><div style={{display:'flex',gap:12,alignItems:'center',marginBottom:22}}><BookOpen color="var(--pink-primary)"/><div><h1 className="jana-page-title" style={{margin:0}}>Contabilidad y conciliación</h1><p style={{margin:'4px 0 0',color:'var(--text-secondary)'}}>Cuentas, libro diario y movimientos bancarios sin mezclar datos simulados.</p></div></div>
  <div style={{display:'grid',gridTemplateColumns:isMobile?'1fr':'repeat(3,1fr)',gap:12,marginBottom:18}}>{[{label:'Por cobrar',value:pending.filter(x=>x.kind==='receivable').reduce((s,x)=>s+Number(x.amount)-Number(x.paid_amount),0)},{label:'Por pagar',value:pending.filter(x=>x.kind==='payable').reduce((s,x)=>s+Number(x.amount)-Number(x.paid_amount),0)},{label:'Banco sin conciliar',value:data.bank.filter(x=>!x.reconciled).length,count:true}].map(x=><div key={x.label} className="agenda-glass-card" style={{padding:18}}><small style={{color:'var(--text-secondary)'}}>{x.label}</small><div style={{fontSize:24,fontWeight:900,marginTop:5}}>{x.count?x.value:`$${x.value.toFixed(2)}`}</div></div>)}</div>
  <div style={{display:'flex',gap:8,marginBottom:14}}>{[['receivables','Cuentas'],['journal','Libro diario'],['bank','Banco'],['accounts','Plan de cuentas']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{border:0,borderRadius:12,padding:'10px 14px',background:tab===id?'var(--pink-primary)':'#fff',color:tab===id?'#fff':'var(--text-primary)',fontWeight:700,cursor:'pointer'}}>{label}</button>)}</div>
  {tab==='receivables'&&<div style={{display:'grid',gridTemplateColumns:isMobile?'1fr':'340px 1fr',gap:18}}><section className="agenda-glass-card" style={{padding:18}}><h3><Plus size={16}/> Registrar cuenta</h3><div style={{display:'grid',gap:10}}><select style={field} value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="receivable">Por cobrar</option><option value="payable">Por pagar</option></select><input style={field} placeholder="Cliente o proveedor" value={form.counterparty} onChange={e=>setForm({...form,counterparty:e.target.value})}/><input style={field} placeholder="Concepto" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input style={field} type="number" placeholder="Monto USD" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input style={field} type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/><button className="btn-pink" onClick={save} style={{height:42,borderRadius:12}}>Guardar</button></div></section><List rows={data.items} empty="No hay cuentas registradas" render={x=><><strong>{x.counterparty}</strong><div>{x.description}</div><small>{x.kind==='receivable'?'Por cobrar':'Por pagar'} · ${Number(x.amount).toFixed(2)} · {x.due_date||'Sin vencimiento'}</small></>}/></div>}
  {tab==='journal'&&<><div className="agenda-glass-card" style={{padding:16,display:'grid',gridTemplateColumns:isMobile?'1fr':'2fr 1fr 1fr 1fr auto',gap:8,marginBottom:12}}><input style={field} placeholder="Concepto del asiento" value={journal.description} onChange={e=>setJournal({...journal,description:e.target.value})}/><select style={field} value={journal.debit_account} onChange={e=>setJournal({...journal,debit_account:e.target.value})}><option value="">Cuenta Debe</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.code} {a.name}</option>)}</select><select style={field} value={journal.credit_account} onChange={e=>setJournal({...journal,credit_account:e.target.value})}><option value="">Cuenta Haber</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.code} {a.name}</option>)}</select><input style={field} type="number" placeholder="Monto" value={journal.amount} onChange={e=>setJournal({...journal,amount:e.target.value})}/><button className="btn-pink" onClick={postJournal}>Contabilizar</button></div><List rows={data.entries} empty="Todavía no hay asientos contables" icon={<ReceiptText/>} render={x=><><strong>{x.entry_date} · {x.description}</strong>{x.journal_lines?.map(l=><div key={l.id}><small>{l.chart_of_accounts?.code} {l.chart_of_accounts?.name}: Debe ${Number(l.debit).toFixed(2)} / Haber ${Number(l.credit).toFixed(2)}</small></div>)}</>}/></>}
  {tab==='bank'&&<><div className="agenda-glass-card" style={{padding:16,marginBottom:12}}><strong>Importar estado de cuenta CSV</strong><div style={{fontSize:11,color:'var(--text-secondary)',margin:'4px 0 10px'}}>Columnas admitidas: fecha, descripcion, monto, referencia.</div><input type="file" accept=".csv,text/csv" onChange={importBank}/></div><List rows={data.bank} empty="Importa movimientos bancarios para conciliarlos" icon={<Landmark/>} render={x=><><strong>{x.transaction_date} · ${Number(x.amount).toFixed(2)}</strong><div>{x.description}</div><small>{x.reconciled?'Conciliado':'Pendiente de conciliación'}</small></>}/></>}
  {tab==='accounts'&&<List rows={data.accounts} empty="Sin plan de cuentas" render={x=><><strong>{x.code} · {x.name}</strong><div style={{textTransform:'capitalize'}}>{x.account_type}</div></>}/>}</div>;
}

function List({rows,empty,render,icon}){return <section style={{display:'grid',gap:10,alignContent:'start'}}>{rows.length===0?<div className="agenda-glass-card" style={{padding:30,textAlign:'center',color:'var(--text-secondary)'}}>{icon}{empty}</div>:rows.map(x=><div key={x.id} className="agenda-glass-card" style={{padding:16}}>{render(x)}</div>)}</section>}
