import React, { useEffect, useState } from 'react';
import { Save, Sliders } from 'lucide-react';
import { dataService } from '../services/dataService';

export default function SettingsModule() {
  const [values,setValues]=useState({ official_rate_source:'BCV', laser_worker_pct:'30', laser_partner_pct:'40', laser_studio_pct:'30', laser_session_interval_days:'21', laser_expiration_months:'10' });
  const [saved,setSaved]=useState(false);
  useEffect(()=>{ Promise.all(Object.keys(values).map(async key=>[key,await dataService.getSystemSetting(key,values[key])])).then(rows=>setValues(Object.fromEntries(rows))).catch(console.error); },[]);
  const save=async()=>{ await Promise.all(Object.entries(values).map(([k,v])=>dataService.setSystemSetting(k,v))); setSaved(true); setTimeout(()=>setSaved(false),1800); };
  const input={height:42,border:'1px solid var(--border-color)',borderRadius:12,padding:'0 12px',width:'100%'};
  return <div className="animate-fade-in"><div style={{display:'flex',gap:12,alignItems:'center',marginBottom:22}}><Sliders color="var(--pink-primary)"/><div><h1 className="jana-page-title" style={{margin:0}}>Configuración</h1><p style={{margin:'4px 0 0',color:'var(--text-secondary)'}}>Reglas operativas oficiales de JanaStudio.</p></div></div><div className="agenda-glass-card" style={{padding:24,maxWidth:720}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:16}}><label>Fuente oficial<select style={input} value={values.official_rate_source} onChange={e=>setValues({...values,official_rate_source:e.target.value})}><option value="BCV">BCV</option></select></label><label>Intervalo láser (días)<input style={input} type="number" value={values.laser_session_interval_days} onChange={e=>setValues({...values,laser_session_interval_days:e.target.value})}/></label><label>Vencimiento (meses)<input style={input} type="number" value={values.laser_expiration_months} onChange={e=>setValues({...values,laser_expiration_months:e.target.value})}/></label><label>Trabajadora %<input style={input} type="number" value={values.laser_worker_pct} onChange={e=>setValues({...values,laser_worker_pct:e.target.value})}/></label><label>Socia/insumos %<input style={input} type="number" value={values.laser_partner_pct} onChange={e=>setValues({...values,laser_partner_pct:e.target.value})}/></label><label>Estudio %<input style={input} type="number" value={values.laser_studio_pct} onChange={e=>setValues({...values,laser_studio_pct:e.target.value})}/></label></div><button className="btn-pink" onClick={save} style={{marginTop:20,height:44,borderRadius:12}}><Save size={16}/> {saved?'Guardado':'Guardar configuración'}</button></div></div>;
}
