-- Fix services name and description encoding issues
UPDATE janastudio.services SET 
  name = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(
    name, 
    'Depilaci??n', 'Depilación'),
    'depilaci??n', 'depilación'),
    'Dise??o', 'Diseño'),
    'dise??o', 'diseño'),
    'U??as', 'Uñas'),
    'u??as', 'uñas'),
    'Pesta??as', 'Pestañas'),
    'pesta??as', 'pestañas'),
    'Hidrataci??n', 'Hidratación'),
    'hidrataci??n', 'hidratación'),
    '??rea', 'área'),
    'aplicaci??n', 'aplicación'),
    'exfoliaci??n', 'exfoliación'),
    'manicur??a', 'manicura'),
    'pedicur??a', 'pedicura'),
    '??tem', 'Ítem'),
    'Â¿', '¿'),
  description = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(
    description, 
    'Depilaci??n', 'Depilación'),
    'depilaci??n', 'depilación'),
    'Dise??o', 'Diseño'),
    'dise??o', 'diseño'),
    'U??as', 'Uñas'),
    'u??as', 'uñas'),
    'Pesta??as', 'Pestañas'),
    'pesta??as', 'pestañas'),
    'Hidrataci??n', 'Hidratación'),
    'hidrataci??n', 'hidratación'),
    '??rea', 'área'),
    'aplicaci??n', 'aplicación'),
    'exfoliaci??n', 'exfoliación'),
    'manicur??a', 'manicura'),
    'pedicur??a', 'pedicura'),
    '??tem', 'Ítem'),
    'Â¿', '¿');

-- Fix inventory name and category encoding issues
UPDATE janastudio.inventory SET 
  name = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(
    name, 
    'Depilaci??n', 'Depilación'),
    'depilaci??n', 'depilación'),
    'Dise??o', 'Diseño'),
    'dise??o', 'diseño'),
    'U??as', 'Uñas'),
    'u??as', 'uñas'),
    'Pesta??as', 'Pestañas'),
    'pesta??as', 'pestañas'),
    'Hidrataci??n', 'Hidratación'),
    'hidrataci??n', 'hidratación'),
    '??rea', 'área'),
    'aplicaci??n', 'aplicación'),
    'exfoliaci??n', 'exfoliación'),
    'manicur??a', 'manicura'),
    'pedicur??a', 'pedicura'),
    '??tem', 'Ítem'),
    'Â¿', '¿'),
  category = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(
    category, 
    'Depilaci??n', 'Depilación'),
    'depilaci??n', 'depilación'),
    'Dise??o', 'Diseño'),
    'dise??o', 'diseño'),
    'U??as', 'Uñas'),
    'u??as', 'uñas'),
    'Pesta??as', 'Pestañas'),
    'pesta??as', 'pestañas'),
    'Hidrataci??n', 'Hidratación'),
    'hidrataci??n', 'hidratación'),
    '??rea', 'área'),
    'aplicaci??n', 'aplicación'),
    'exfoliaci??n', 'exfoliación'),
    'manicur??a', 'manicura'),
    'pedicur??a', 'pedicura'),
    '??tem', 'Ítem'),
    'Â¿', '¿');
